
version: 2.1

jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.9

    steps:
      - checkout

      - run: |
         CLOUDSMITH_API_KEY=$(curl -X POST -H "Content-Type: application/json" -d "{\"oidc_token\":\"$CIRCLE_OIDC_TOKEN_V2\", \"service_slug\":\"circleci-0yjm\"}" https://api.cloudsmith.io/openid/demo/ | jq -r '.token')
         poetry source add --priority=primary cloudsmith https://dl.cloudsmith.io/basic/demo/circle-ci/python/simple/ 
         poetry config http-basic.cloudsmith circleci-0yjm $CLOUDSMITH_API_KEY 
         poetry install

      - run:
          name: Run tests
          # This assumes pytest is installed via the install-package step above
          command: pytest

workflows:
  build: 
    jobs:
      - build-and-test