
version: 2.1

jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.9

    steps:
      - checkout

      - run: |
         CLOUDSMITH_API_KEY=$(curl -X POST -H "Content-Type: application/json" -d "{\"oidc_token\":\"$CIRCLE_OIDC_TOKEN_V2\", \"service_slug\":\"circleci-0yjm\"}" https://api.cloudsmith.io/openid/demo/ | jq -r '.token')
         poetry source add --priority=primary cloudsmith https://dl.cloudsmith.io/basic/demo/circle-ci/python/simple/ 
         poetry config http-basic.cloudsmith circleci-0yjm $CLOUDSMITH_API_KEY 
         poetry install

         # stop the build if there are Python syntax errors or undefined names
         flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
         
         # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
         flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - run:
          name: Run tests
          # This assumes pytest is installed via the install-package step above
          command: pytest

workflows:
  build: 
    jobs:
      - build-and-test