# This workflow will install Python dependencies, and run tests with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]

permissions:
  id-token: write
  actions: write       # Necessary to cancel workflow executions
  contents: read

env:
  CLOUDSMITH_SERVICE: gh-actions

jobs:
  build:

    runs-on: ubuntu-latest
    environment: dev

    steps:
    - uses: actions/checkout@v4

    - name: Auth to Cloudsmith with OIDC
      uses: cloudsmith-io/cloudsmith-cli-action@v1.0.2
      with:
        oidc-namespace: 'demo'
        oidc-service-slug: ${{ env.CLOUDSMITH_SERVICE }}
        oidc-auth-only: 'true'
        
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"
        
    - name: Install dependencies
      run: |
        pip install -r requirements.txt --index-url https://$CLOUDSMITH_SERVICE:$CLOUDSMITH_API_KEY@dl.cloudsmith.io/basic/demo/gh-actions/python/simple/
    
    - name: Test with pytest
      run: |
        pytest
